/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VIEW;

import MODELS.contaModel;
import REPOSITORY.contaRepository;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class tabelaContas extends javax.swing.JInternalFrame {

    /**
     * Creates new form tabelaContas
     */
    public tabelaContas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtconta = new javax.swing.JTextField();
        txtpreco = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableconta = new javax.swing.JTable();
        cadastarTableConta = new javax.swing.JButton();
        excluirTableConta = new javax.swing.JButton();
        btnDadosConta = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setText("CONTA");

        jLabel2.setText("PREÇO");

        txtconta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontaActionPerformed(evt);
            }
        });

        tableconta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CONTA", "PREÇO"
            }
        ));
        jScrollPane1.setViewportView(tableconta);

        cadastarTableConta.setText("Cadastrar");
        cadastarTableConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastarTableContaActionPerformed(evt);
            }
        });

        excluirTableConta.setText("Excluir");
        excluirTableConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirTableContaActionPerformed(evt);
            }
        });

        btnDadosConta.setText("Carregar dados");
        btnDadosConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDadosContaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cadastarTableConta, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDadosConta, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(excluirTableConta, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtconta, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtpreco, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtconta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastarTableConta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(excluirTableConta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDadosConta, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastarTableContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastarTableContaActionPerformed
        String contas = txtconta.getText();
        String preco = txtpreco.getText();
        
        contaModel sistemaCerto = new contaModel(contas,preco);
        
        contaRepository repository = new contaRepository();
        
        repository.CreateContas(sistemaCerto);
        
       txtconta.setText("");
       txtpreco.setText("");
    }//GEN-LAST:event_cadastarTableContaActionPerformed

    private void excluirTableContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirTableContaActionPerformed
        
        if(tableconta.getSelectedRow() != -1){
        
DefaultTableModel dtmProdutos = (DefaultTableModel) tableconta.getModel();
dtmProdutos.removeRow(tableconta.getSelectedRow());
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um produto pra excluir.");
        }
        
        
    }//GEN-LAST:event_excluirTableContaActionPerformed

    private void txtcontaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontaActionPerformed

    private void btnDadosContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadosContaActionPerformed
 
        try {
            contaRepository contarepositorio = new contaRepository();
           List<contaModel> listaconta = contarepositorio.readAllConta();
            DefaultTableModel tableConta
                    = (DefaultTableModel) tableconta.getModel();
            tableConta.setNumRows(0);
            for (contaModel ContaModel : listaconta) {
                Object[] novoProduto = new Object[]{
                    ContaModel.getConta(), ContaModel.getPreco()
                };
                tableConta.addRow(novoProduto);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro");
        }


        
    }//GEN-LAST:event_btnDadosContaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDadosConta;
    private javax.swing.JButton cadastarTableConta;
    private javax.swing.JButton excluirTableConta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableconta;
    private javax.swing.JTextField txtconta;
    private javax.swing.JTextField txtpreco;
    // End of variables declaration//GEN-END:variables
}
